POST http://localhost:8080/purchase/items
Content-Type: application/json

{
  "name": "item-4",
  "comment": "comment-4"
}

###
GET http://localhost:8080/purchase/items
Accept: application/json

###

PUT http://localhost:8080/purchase/items/1
Content-Type: application/json

{
  "name": "item-updated",
  "comment": "comment-updated"
}

###
### customer
POST http://localhost:8080/purchase/customers
Content-Type: application/json

{
  "name": "Customer-1",
  "address": "address",
  "fax": "fax",
  "tel": "04-242423",
  "contact": "contactor",
  "contactPhone": "0912-345689",
  "contactEmail": "abc@123.com",
  "taxIdNumber": "12384706",
  "comment": "comment"
}

###
GET http://localhost:8080/purchase/customers
Accept: application/json

###

PUT http://localhost:8080/purchase/customers/1
Content-Type: application/json

{
  "name": "Customer-1-updated",
  "address": "address-updated",
  "fax": "fax-updated",
  "tel": "04-242423",
  "contact": "contactor",
  "contactPhone": "0912-345689",
  "contactEmail": "abc@123.com",
  "taxIdNumber": "12384706",
  "comment": "comment"
}

###
### Purchase Order
POST http://localhost:8080/purchase/orders
Content-Type: application/json

{
  "poNumber": "2022031900001",
  "purchaseDate": "2022-03-19",
  "purchaseCustomerId": 1,
  "purchaseItemId": 1,
  "unitId": 1,
  "quantity": 500,
  "price": 500,
  "totalAmount": 25000,
  "comment": "comment"
}

###
GET http://localhost:8080/purchase/orders
Accept: application/json

###

PUT http://localhost:8080/purchase/orders/1
Content-Type: application/json

{
  "poNumber": "2022031900002",
  "purchaseDate": "2022-03-20",
  "purchaseCustomerId": 1,
  "purchaseItemId": 1,
  "unitId": 1,
  "quantity": 100,
  "price": 700,
  "totalAmount": 70000,
  "comment": "comment-update"
}
