POST http://localhost:8080/purchase/items
Content-Type: application/json

{
  "name": "item-1",
  "comment": "comment"
}

###
GET http://localhost:8080/purchase/items
Accept: application/json

###

PUT http://localhost:8080/purchase/items/1
Content-Type: application/json

{
  "name": "item-updated",
  "comment": "comment-updated"
}

###
### customer
POST http://localhost:8080/purchase/customers
Content-Type: application/json

{
  "name": "Customer-1",
  "address": "address",
  "fax": "fax",
  "tel": "04-242423",
  "contact": "contactor",
  "contactPhone": "0912-345689",
  "contactEmail": "abc@123.com",
  "taxIdNumber": "12384706",
  "comment": "comment"
}

###
GET http://localhost:8080/purchase/customers
Accept: application/json

###

PUT http://localhost:8080/purchase/customers/1
Content-Type: application/json

{
  "name": "Customer-1-updated",
  "address": "address-updated",
  "fax": "fax-updated",
  "tel": "04-242423",
  "contact": "contactor",
  "contactPhone": "0912-345689",
  "contactEmail": "abc@123.com",
  "taxIdNumber": "12384706",
  "comment": "comment"
}
