CREATE TABLE IF NOT EXISTS purchase_item
(
  id
  INT
  AUTO_INCREMENT
  PRIMARY
  KEY,
  name
  VARCHAR
(
  255
) NOT NULL,
  status TINYINT DEFAULT 1,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  ) ENGINE = INNODB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_unicode_520_ci;
