version: "3.8"
services:
  db:
    container_name: will-win-db
    image: "mysql:5.6"
    ports:
      - "3306:3306"
    volumes:
      - will-win-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql

volumes:
  will-win-mysql:
    external: true
    name: will-win-mysql
