version: "3.8"
services:
  db:
    container_name: will-win-db
    image: "mysql:8.0.28"
    ports:
      - "3306:3306"
    volumes:
      - will-win-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql

volumes:
  will-win-mysql-data:

